language: java
jdk:
- oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


before_deploy:
  - "mv build/libs/awsokta-stage-exec.jar build/libs/awsokta-exec.jar"
#  - export FOO=$(ls build/libs/aws*.jar)

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file:  'build/libs/awsokta-exec.jar'
  skip_cleanup: true
  on:
    repo: ayavorsk2000-gmail/awsokta
    tags: true
